---
- name: Copy file to a remote machine 
  copy: 
    src: files/pacman_mirrorlist
    dest: /etc/pacman.d/mirrorlist
    force: yes

- name: Update Pacman & packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install Packages
  pacman:
    name: '{{ item }}'
    state: present
  with_items: '{{ pacman_packages }}'
  ignore_errors: yes
