---
- name: ensure we have directory for vnc service
  file:
    path: /etc/systemd/user
    state: directory

- name: Create user service for vncserver keys
  copy: 
    src: files/x0vncserver_service
    dest: /etc/systemd/user/x0vncserver.service
    force: yes

- name: Start vncservershd servce
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: x0vncserver.service
    scope: user
  environment:
    XDG_RUNTIME_DIR: /run/user/1000
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  become: yes
  become_user: nick

