- name: Start transmission daemon
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: transmission.service
    scope: user
  environment:
    XDG_RUNTIME_DIR: /run/user/1000
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  become: yes
  become_user: nick