---
- name: Copy file to a remote machine 
  copy: 
    src: files/pacman_mirrorlist
    dest: /etc/pacman.d/mirrorlist
    force: yes

- name: Update Pacman
  pacman:
    update_cache: yes

- name: Install Packages
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ must_haves }}'
  ignore_errors: yes

